### PR TITLE
Download story

### LINKED ISSUE #138: Enable export/download of story in builder as html/json file(s)
Once a story is built, it should be possible to export it as html/json so it can be sent to us for uploading/publishing.

### PR DESCRIPTION
**Pull request by sjvrijn**
### What this PR does

Fixes RECEIPT-H2020/TerriaMap#138 

- Added an AWS Lambda function 'zipStory' that zips all relevant files for a story, stores that zip publically accessible in the s3 bucket and returns the URL
- Added a 'Download (.zip)' button in RCStoryEditor that calls the lambda above and triggers the download of the returned URL

Also: 
- Added explicit (now functioning) call to `buildStaticStory` lambda function to generate initfile.json and put all files in correct place
- Minor update to `buildStaticStory`'s page-to-HTML conversion: can now also convert if a page does not have scenarios (old pages with scenarios will still work too)
- Removed separate 'Publish' button.

### Questions

1. Can someone also double-check some of the AWS policy/permissions I've had to set?
2. Most AWS-stuff seems to be 'devel' environment related. Are we using that environment for 'production' too, or do some things still have to be changed for actual deployment?

### Further details

The `zipStory` lambda function worked without issue when mocking locally, but needed some additional IAM permissions to work when deployed:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ExampleStmt",
            "Action": [
                "s3:GetObject",     # not sure if this is strictly needed
                "s3:PutObject",
                "s3:PutObjectAcl"   # allow setting permissions of uploaded zip to 'public-read'
            ],
            "Effect": "Allow",
            "Resource": [
                "<<S3BucketARN>>"
            ]
        }
    ]
}
```

There's also been some policy stuff I've been changing, which I could look up if needed.

### CODE REVIEW

**Comment by kretep** [comment]
@sjvrijn Looking into this now, but when I click the "publish" button, I get an error when the lambda function is being called: POST https://vyx4jioz3grqloqlvhirjbmfw40ichyd.lambda-url.eu-central-1.on.aws/ 502 (Bad Gateway)

**Comment by sjvrijn** [comment]
@kretep Eh... there should not be a publish button?

**Comment by kretep** [comment]
Interesting. Something seems to be glitchy when switching to a different branch (have a similar issue with the other branch). Not sure why it doesn't update

**Review by kretep — APPROVED** [review]

**Comment by kretep** [comment]
Managed to get it to run (there was an old instance running that really didn't want to be killed) and it works as expected!

**Pull request merged**
