### PR TITLE
Feature/hotspot summary

### PR DESCRIPTION
**Pull request by ctwhome**
image

### CODE REVIEW

**Review by bpmweel — CHANGES_REQUESTED** [review]
It looks good on normal screen, but it does not work in portrait mode in mobile size. The story summary is not shown.

Screenshot 2020-08-31 at 10 44 00

**Comment by ctwhome** [comment]
Fixed!
image

**Review by Maartenvm — CHANGES_REQUESTED** [review]
I'm getting errors when building

base  maarten  DESKTOP-MGB32VT  ~  workspace  …  TerriaMap  packages  terriajs  feature/hotspot-summary  $   npx gulp
[15:26:02] Using gulpfile ~/workspace/receipt-platform/TerriaMap/packages/terriajs/gulpfile.js
[15:26:02] Starting 'default'...
[15:26:02] Starting 'lint'...

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/Map/MapNavigation.jsx
   1:8   warning  'Compass' is defined but never used             no-unused-vars
   3:8   warning  'MyLocation' is defined but never used          no-unused-vars
   9:8   warning  'ToggleSplitterTool' is defined but never used  no-unused-vars
  10:8   warning  'ViewerMode' is defined but never used          no-unused-vars
  44:14  warning  Expected space or tab after '/*' in comment     spaced-comment

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/Map/MenuBar.jsx
    7:8   warning  'HelpMenuPanelBasic' is defined but never used                  no-unused-vars
    9:8   warning  'SettingPanel' is defined but never used                        no-unused-vars
   10:8   warning  'SharePanel' is defined but never used                          no-unused-vars
   12:8   warning  'Icon' is defined but never used                                no-unused-vars
   14:8   warning  'Prompt' is defined but never used                              no-unused-vars
   66:13  warning  't' is assigned a value but never used                          no-unused-vars
   67:11  warning  'satelliteGuidancePrompted' is assigned a value but never used  no-unused-vars
   70:11  warning  'mapGuidesLocationPrompted' is assigned a value but never used  no-unused-vars
   76:11  warning  'promptHtml' is assigned a value but never used                 no-unused-vars
   94:11  warning  'delayTime' is assigned a value but never used                  no-unused-vars
  105:12  warning  Expected space or tab after '/*' in comment                     spaced-comment
  127:12  warning  Expected space or tab after '/*' in comment                     spaced-comment
  134:12  warning  Expected space or tab after '/*' in comment                     spaced-comment
  140:12  warning  Expected space or tab after '/*' in comment                     spaced-comment
  150:12  warning  Expected space or tab after '/*' in comment                     spaced-comment

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/Map/RCMenuBar.jsx
   7:11  error  'viewState' is missing in props validation                     react/prop-types
  14:33  error  'viewState.isHotspotsFiltered' is missing in props validation  react/prop-types
  19:17  error  'viewState.isHotspotsFiltered' is missing in props validation  react/prop-types
  22:15  error  'viewState.isHotspotsFiltered' is missing in props validation  react/prop-types
  29:19  error  'viewState.topElement' is missing in props validation          react/prop-types

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/Map/TerriaViewerWrapper.jsx
  76:12  warning  Expected space or tab after '/*' in comment  spaced-comment

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/RCFeatureInfo/FeatureInfoPanel.jsx
   26:8   warning  'triggerResize' is defined but never used  no-unused-vars
   31:10  warning  'launchStory' is defined but never used    no-unused-vars
  340:5   warning  Unreachable code                           no-unreachable

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/RCHotspotSummary/RCHotspotSummary.jsx
  38:11  warning  'type' is assigned a value but never used  no-unused-vars

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/SidePanel/SectorInfo.jsx
  18:70  error  'close' is missing in props validation  react/prop-types

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/SidePanel/SectorTabs.jsx
  20:22  warning  'viewState' is not defined  jsx-control-statements/jsx-jcs-no-undef

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/SidePanel/SidePanelContent.jsx
  19:22  warning  'viewState' is not defined  jsx-control-statements/jsx-jcs-no-undef

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx
   9:8  warning  'ExplorerWindow' is defined but never used        no-unused-vars
  11:8  warning  'FeedbackForm' is defined but never used          no-unused-vars
  16:8  warning  'ExperimentalFeatures' is defined but never used  no-unused-vars
  25:8  warning  'StoryPanel' is defined but never used            no-unused-vars

/home/maarten/workspace/receipt-platform/TerriaMap/packages/terriajs/lib/ReactViews/Story/RCStoryPanel.jsx
  7:10  warning  'Small' is defined but never used  no-unused-vars

✖ 38 problems (6 errors, 32 warnings)
  0 errors and 7 warnings potentially fixable with the `--fix` option.

[15:26:32] 'lint' errored after 29 s
[15:26:32] Error in plugin "eslint/bin/eslint.js"
Message:
    External module exited with an error.
Details:
    domain: [object Object]
    domainThrown: true

[15:26:32] 'default' errored after 29 s

**Comment by bpmweel** [comment]
> I'm getting errors when building

I have been only testing by building from the TerriaMap directory, which does not do the extensive linting apparently. I think that means multiple linting errors krept in from other pull requests

It's probably good to fix the linting errors, hope Jesus doesn't mind fixing them, otherwise we could open a new issue for it.

**Comment by ctwhome** [comment]
I can take care of it, now that Peter and I are pair programming :)

**Comment by kretep** [comment]
:pear::pear::pear:

**Comment by Maartenvm** [comment]
Lol it took me way too long to get pear programming :P

**Comment by ctwhome** [comment]
Fixed lint and console app errors as well: 
image

**Review by Maartenvm — APPROVED** [review]
I can't help but notice that you also fixed the tooltip in this same pull request which is kind of against the agreements, but in this case I'll allow it, thanks :)

**Pull request merged**
