### PR TITLE
Navigation topbar

### LINKED ISSUE #119: Improve story pages navigations and sections

### PR DESCRIPTION
**Pull request by sjvrijn**
_This PR supercedes #96_

Fixes https://github.com/RECEIPT-H2020/TerriaMap/issues/119, https://github.com/RECEIPT-H2020/TerriaMap/issues/128, https://github.com/RECEIPT-H2020/TerriaMap/issues/135

This PR contains the following changes:

Footer:
- [x] Remove navigation circles from footer
- [x] 'Previous' and 'Next' icons replaced by text and made larger
- [x] Add page counter
- [x] Tidy up lay-out

Header:
- [x] Move out of StoryPanel to a separate full-width navigation header
- Also for the story-selection pages!
- [x] Change section buttons to arrows
- [x] Include small arrows for additional pages per section
- [x] Move Receipt logo out of map and into navigation header

ToDo:
- [x] Make map-zoom buttons move with the map
- [x] Make sector-name tooltips z-index *above* storypanel

### CODE REVIEW

**Comment by sjvrijn** [comment]
Was not able to fix the tooltip issue through z-indexes, but there was enough room to move them a bit so they are no longer occluded.

**Comment by sjvrijn** [comment]
also fixes https://github.com/RECEIPT-H2020/TerriaMap/issues/113

**Comment by sjvrijn** [comment]
@goord @kretep Could you review this? Thanks!

**Comment by kretep** [comment]
@sjvrijn I get an error on the first soy story (/sector/agriculture/story/1/page/0); not sure what is different there. It seems to work for the other stories

**Comment by kretep** [comment]
The desktop version seems to work fine. Maybe we could consider putting the logo inside the header (it's a bit asymmetric now). On mobile, it seems the header takes too much space, and scrolling is not always working properly

**Comment by kretep** [comment]
On the coastal flood story, the last section/page arrow is black. I don't think it is supposed to be?

image

**Comment by sjvrijn** [comment]
> @sjvrijn I get an error on the first soy story (/sector/agriculture/story/1/page/0); not sure what is different there. It seems to work for the other stories

That story also seems to fail on the `receipt` branch, but it does seem to fail differently there?
I'll have a look either way

> The desktop version seems to work fine. Maybe we could consider putting the logo inside the header (it's a bit asymmetric now). On mobile, it seems the header takes too much space, and scrolling is not always working properly

I'm not sure putting the logo in the header will look better, but I'll make a mock-up so we can compare 👍 
I have so far not taken the view on mobile into account, since @goord mentioned it was not a priority, but I can imagine the current navigation header being too big for mobile view. That should probably become a dropdown table instead.

> On the coastal flood story, the last section/page arrow is black. I don't think it is supposed to be?

Indeed it isn't. In which browser is that? I don't get that in either Chrome or Firefox on my Dell

**Comment by kretep** [comment]
> That story also seems to fail on the `receipt` branch, but it does seem to fail differently there? I'll have a look either way

Maybe something went wrong on the `receipt` branch then. On the deployed version it is still working.

> Indeed it isn't. In which browser is that? I don't get that in either Chrome or Firefox on my Dell

In Chrome. In other stories it does work properly. I see it has an `undefined` class entry on the div, so maybe there's typo in a section identifier? (Using TerriaMap on the latest `receipt` branch)
image

**Comment by goord** [comment]
One thing to note: I added a conclusion section to the receipt terriajs branch. Also, the displayed names were changed there...

**Comment by sjvrijn** [comment]
> One thing to note: I added a conclusion section to the receipt terriajs branch. Also, the displayed names were changed there...

Yes, I noticed and fixed that in the merge (2e31387) :+1:
Am now trying to find where in TerriaMap story 1 was broken.

**Comment by goord** [comment]
I have tested this locally and I am enthusiastic

**Review by kretep — APPROVED** [review]

**Pull request merged**
